version: '3'

services:
  postgres:
    image: postgres:14
    container_name: ed_local_db
    restart: 'always'
    expose:
      - '5432'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_MULTIPLE_DATABASES="desafio_e2e"
      - POSTGRES_DB=desafio
      - POSTGRES_USER=desafio
      - POSTGRES_PASSWORD=desafio
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./other/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

    #   - ./postgres-data:/var/lib/postgresql/data