version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: ed_local_db
    restart: 'always'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=desafio
      - POSTGRES_USER=desafio
      - POSTGRES_PASSWORD=desafio
    # volumes:
      # - db:/var/lib/postgresql/data
# volumes:
#   db:
#     driver: local
