-- AlterTable
ALTER TABLE "ParticipantDiary" ALTER COLUMN "date" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "ProgramDiary" ALTER COLUMN "date" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "UserDiary" ALTER COLUMN "date" SET DEFAULT CURRENT_TIMESTAMP;
